apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: go-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: sayemiit/auth-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password@mongo-service:27017"
