apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: go-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <YOUR_DOCKER_HUB_USERNAME>/frontend:latest
        ports:
        - containerPort: 80
