apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_GITHUB_USERNAME>/go-todo-k8s.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: go-todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
