apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SAYEM-16T/EKS-GITOPS  # Replace with GitOps repository URL // if needed
    targetRevision: HEAD
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: go-todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true