name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME_AUTH: sayemiit/auth-service
  IMAGE_NAME_FRONTEND: sayemiit/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push auth-service
      run: |
        docker build -t $IMAGE_NAME_AUTH:latest -t $IMAGE_NAME_AUTH:${{ env.SHORT_SHA }} ./auth-service
        docker push $IMAGE_NAME_AUTH:latest
        docker push $IMAGE_NAME_AUTH:${{ env.SHORT_SHA }}

    - name: Build and push frontend
      run: |
        docker build -t $IMAGE_NAME_FRONTEND:latest -t $IMAGE_NAME_FRONTEND:${{ env.SHORT_SHA }} ./frontend
        docker push $IMAGE_NAME_FRONTEND:latest
        docker push $IMAGE_NAME_FRONTEND:${{ env.SHORT_SHA }}

    - name: Clone GitOps repo
      run: |
        git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/SAYEM-16T/K8s_gitOps.git gitops
        cd gitops
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Update manifests in GitOps repo
      run: |
        cd gitops

        sed -i "s|image: $IMAGE_NAME_AUTH:.*|image: $IMAGE_NAME_AUTH:${{ env.SHORT_SHA }}|g" gitops/auth-deployment.yaml
        sed -i "s|image: $IMAGE_NAME_FRONTEND:.*|image: $IMAGE_NAME_FRONTEND:${{ env.SHORT_SHA }}|g" gitops/frontend-deployment.yaml

        git add .
        git commit -m "Update image tags to ${{ env.SHORT_SHA }}"
        git push
